services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /mysql_data2:/var/lib/mysql2
      - ./dbstore:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
    ports:
      - "8086:80"
    depends_on:
      - mysql

  apache:
    build: ./mysql-php
    image: php:8.2-apache
    container_name: apache_container
    volumes:
      - ./mysql-php/app:/var/www/html
    ports:
      - "8085:80"
    depends_on:
      - mysql  